/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

public class App extends Application {
   public String getGreeting() {
        return "Hello World!";
   }

    @Override
    public void start(Stage stage) throws Exception {
        Parent root = FXMLLoader.load(getClass().getResource("guitriki.fxml"));

        //FXMLLoader loader = new FXMLLoader(getClass().getResource("/org/example/tuarchivo.fxml"));


        Scene scene = new Scene(root);

        stage.setTitle("Juego de Triki o tres en raya");
        stage.setScene(scene);
        stage.show();

    }

    public static void main(String[] args) {
        launch(args);
    }

}
